source_db_var: "daphne"
target_db_var: "dwh"

etl_tasks:
  - source_schema: "ocn_cat"
    source_table: "cat_scenario_def"
    target_schema: "ocn_cat"
    target_table: "cat_scenario_def"
    load_method: "create_if_not_exists_or_truncate"

  - source_schema: "ocn_cat"
    source_table: "cat_acquirer_def"
    target_schema: "ocn_cat"
    target_table: "cat_acquirer_def"
    load_method: "create_if_not_exists_or_truncate"

  - source_schema: "ocn_cat"
    source_table: "cat_reason_def" 
    target_schema: "ocn_cat"
    target_table: "cat_reason_def"
    load_method: "create_if_not_exists_or_truncate"

  - source_schema: "ocn_cat"
    source_table: "cat_bank_code_def"
    target_schema: "ocn_cat"
    target_table: "cat_bank_code_def"
    load_method: "create_if_not_exists_or_truncate"

  - source_schema: "ocn_cat"
    source_table: "cat_trnx_def"
    target_schema: "ocn_cat"
    target_table: "cat_trnx_def"
    load_method: "create_if_not_exists_or_truncate"
  